### ISSUE TITLE
Maintenance / HTML5 Destructible Terrain question

### ISSUE THREAD

**Issue by mbforbes** [drkibitz/openfl-napesamples#2]
Hi,

First, thanks so much for putting this together! I had been spending a while trying to do exactly this, and finding your code helped a ton and saved a huge amount of time.

I have two questions.

First, are you interested in maintaining this at all? It's interesting to me that OpenFl's main GitHub page boasts NAPE as one of its supported libraries, but we can see here how much work has to be done to get it to actually function. There are some minor changes that need to be made (e.g. use 'lime' to build, some examples run incorrectly), and I also wonder if the OpenFl support that was lacking 1/2 a year ago could have improved.

Second, could you give me any more info as to why the Destructible Terrain doesn't work for 'html5'? I was hoping to write in Haxe and build to JavaScript, and that example was exactly the one I was hoping to base code on, and it doesn't work! Incorporating some of your changes and building myself I just get a bunch of squares and no perlin noise & no ability to made holes or spawn objects. My best guess was that bitmap operations aren't working for Javascript?

Thanks for reading such a long comment, and regardless, thank you for your work on this!

Cheers,
Max

**Comment by drkibitz** [comment]
@mbforbes Oh my! I know this is going on 13 months late, but I completely missed this!

Please, I hope you accept my humblest and thousand apologies. I do not usually do that :sob: 

This repo got lost to me, and I'm not sure why, but honestly Github decided not to send me anything or post a notification of this to me.

---

What has been going on in the last 13 months? Did you change direction, did you continue researching?

**Comment by mbforbes** [comment]
Hey @drkibitz,

No peoblem about the late reply! Sorry mine is late as well. I have to admit that a day or two after writing the above comment I changed direction. Haxe just didn't seem easy enough to use in a truly cross-platform way. (Not that I blame them; I would imagine it's really hard.)

Anyway, thanks for ending up getting back to me! I will be curious if support widens eventually.

Warm regards,
Max
